language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
 - sudo apt-get update
 - sudo apt-get install ledger
 - sudo apt-get install hledger
 - pip install poetry
 - pip install --upgrade pip
install: poetry install
# command to run tests
script: poetry run python -m pytest
